imgtool: max alignment to 128 bytes for Renesas
write-block-size is set to 128 bytes for the ra4, ra6, ra8's flash0
dtsi.

Fix error:
  Error: Invalid value for '--align': '128' is not one of '1', '2', '4', '8', '16', '32'.

Signed-off-by: Vincent Jardin <vjardin@free.fr>