repository.yml: Remove invalid stability "rc1"
Newt only allows the following stability strings in a repo version:

    VERSION_STABILITY_NONE   = ""
    VERSION_STABILITY_STABLE = "stable"
    VERSION_STABILITY_DEV    = "dev"
    VERSION_STABILITY_LATEST = "latest"
    VERSION_STABILITY_COMMIT = "commit"

An attempt to update a project that uses mcuboot would choke due to the
invalid stability string "rc1":

    Error: Unknown stability (rc1) in version 1.3.0-rc1

Signed-off-by: Christopher Collins <ccollins@apache.org>