bootutil: imgtool: Fix CI failures
For some platorms
image_validate.c: In function 'bootutil_img_validate':
image_validate.c:358:40: error: 'image_index' undeclared
(first use in this function); did you mean 'image_header'?
  358 |             key_id = bootutil_find_key(image_index, buf, len);
      |                                        ^~~~~~~~~~~

Resolve imgtool CI errors affecting certain signature verification tests.

Change the return type of boot_verify_key_id_for_image to reflect
its use as an FIH call.

Add new bootutil source files to the Zephyr and
espressif CMakeLists.txt files to fix undefined symbols.

Update FIH tests to use the latest TFM version. This also requires
updating the toolchain version to 14.2 in the Docker image.

Signed-off-by: Maulik Patel <maulik.patel@arm.com>
Change-Id: Ie75e6c533631b2696a4a41d86b64d4009fac0c54