Build: Fix build error when BOOT_IMAGE_NUMBER=1
When MCUboot is build with single image -DMCUBOOT_IMAGE_NUMBER=1,
then build fails with error:
'struct boot_loader_state' has no member named 'curr_img_idx'

'curr_img_idx' is only defined when BOOT_IMAGE_NUMBER > 1. This patch
fixes the build error by using already defined image index macro
which passes 0 when single image is built else appropriate image index.

Signed-off-by: Maulik Patel <maulik.patel@arm.com>
Change-Id: I221ebbd6f2cb5f835ab2576036ec70280e2d6778