bootutil: loader: fix: compile for single slot encrypted message
Recent improvements broke single slot image.

Fixes

```
bootloader/mcuboot/boot/boot_serial/src/boot_serial.c:691:
undefined reference to `boot_close_all_flash_areas'
collect2: error: ld returned 1 exit status
```

Signed-off-by: Nerijus Bendžiūnas <nerijus.bendziunas@gmail.com>